//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreMartket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuTraHang
    {
        public string MaPhieuTra { get; set; }
        public string MaNhaCungCap { get; set; }
        public System.DateTime NgayTra { get; set; }
        public int MaNhanVien { get; set; }
        public string LyDoTra { get; set; }
        public string TrangThai { get; set; }
    
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
