//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreMartket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_Machines
    {
        public int MaPOS { get; set; }
        public string MaQuay { get; set; }
        public string TenPOS { get; set; }
        public string SoSeri { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayLapDat { get; set; }
        public Nullable<System.DateTime> LastMaintenance { get; set; }
        public Nullable<int> NhanVienID { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
